### ISSUE TITLE
Error : Can't find the csv file (to convert it to pcap)

### ISSUE THREAD

**Issue by MariMari7** [cslev/pcap_generator#2]
$ python pcap_generator_from_csv.py -i C:\Users\mari\Desktop\Smaller.csv -o C:\Users\mari\Desktop\SmallerPcap
The following arguments were set:
Input file:            C:UsersmariDesktopSmaller.csv
Output file:           C:UsersmariDesktopSmallerPcap
Packetsizes:           ['64']
SRC MAC if undefined:  00:00:00:00:00:01
DST MAC if undefined:  00:00:00:00:00:02
SRC IP if undefined:   10.0.0.1
DST IP if undefined:   10.0.0.2
TTL if undefined:      10
SRC PORT if undefined: 1234
DST PORT if undefined: 80
VLAN if undefined:     None
GTP_TEID if undefined  None
TIMESTAMP if undefined:None
Traceback (most recent call last):
  File "pcap_generator_from_csv.py", line 690, in <module>
    ttl=ttl
  File "pcap_generator_from_csv.py", line 324, in generateTraceFromFile
    headers=readFile(inputfile)
  File "pcap_generator_from_csv.py", line 182, in readFile
    with open(input, 'r') as lines:
FileNotFoundError: [Errno 2] No such file or directory: 'C:UsersmariDesktopSmaller.csv'

**Comment by cslev** [comment]
I made some slight changes to the input argument parsing, however, on my windows machine with Python 3.9, the original version also works normally.
```
C:\Users\lele\pcap_generator>python pcap_generator_from_csv.py -i C:\Users\lele\pcap_generator\input.csv -o asd
[01mThe following arguments were set:[0m
[01mInput file:            [32mC:\Users\lele\pcap_generator\input.csv[0m
[01mOutput file:           [32masd[0m
[01mPacketsizes:           [32m['64'][0m
[01mSRC MAC if undefined:  [32m00:00:00:00:00:01[0m
[01mDST MAC if undefined:  [32m00:00:00:00:00:02[0m
[01mSRC IP if undefined:   [32m10.0.0.1[0m
[01mDST IP if undefined:   [32m10.0.0.2[0m
[01mTTL if undefined:      [32m10[0m
[01mSRC PORT if undefined: [32m1234[0m
[01mDST PORT if undefined: [32m80[0m
[01mVLAN if undefined:     [32mNone[0m
[01mGTP_TEID if undefined  [32mNone[0m
[01mTIMESTAMP if undefined:[32mNone[0m
all-byte packets: 16%
all-byte packets: 33%
all-byte packets: 50%
all-byte packets: 66%
all-byte packets: 83%
all-byte packets: 100%

C:\Users\lele\pcap_generator>
```
If you still have this issue I recommend you copy the CSV file into the main directory of pcap_generator then you don't have to use backslashes.
please, let me know if it works. Thanks

**Comment by MariMari7** [comment]
Hello,

Thank you for reaching out,

I have replaced the Backslashes by Slashes and *IT WORKS*.

File is converted, however, with limited features.

Thank you a lot.



Le jeu. 18 févr. 2021 à 01:38, Levente Csikor <notifications@github.com> a
écrit :

**Comment by cslev** [comment]
Thanks for confirming. 
Only a handful of header fields are supported by this app.
